---

backends:
  cloud_service_monitoring:
    project_id: gplasky-canhaz-coffee

exporters: {}

error_budget_policies:
  default:
    steps:
    - name: c.Last 7 days
      burn_rate_threshold: 1.5
      alert: false
      message_alert: Dev team dedicates 25% of engineers to the reliability backlog
      message_ok: Last week on track
      window: 604800
    - name: d.Last 28 days
      burn_rate_threshold: 1
      alert: false
      message_alert: Freeze release, unless related to reliability or security
      message_ok: Unfreeze release, per the agreed roll-out policy
      window: 2419200
