apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: hipstershop-grpc-availability
  labels:
    service_name: hipstershop
    feature_name: grpc
    slo_name: availability
    metadata:
      env: prod
spec:
  description: Availability of Hipstershop as measured by client RPCs
  backend: cloud_service_monitoring
  method: good_bad_ratio
  exporters: []
  service_level_indicator:
    filter_good: >
      project="gplasky-canhaz-coffee"
      resource.type="global"
      metric.type="custom.googleapis.com/opencensus/grpc.io/client/completed_rpcs"
      metric.labels.grpc_client_method = starts_with("hipstershop")
      metric.labels.grpc_client_status = one_of("OK", "CANCELLED")
    filter_valid: >
      project="gplasky-canhaz-coffee"
      metric.type="custom.googleapis.com/opencensus/grpc.io/client/completed_rpcs"
      resource.type="global"
  goal: 0.995
